### ISSUE TITLE
Why typescript in dependencies?

### ISSUE THREAD

**Issue by moochannel** [aspida/eslint-plugin-aspida#6]
## Description

I am using Typescript 4.3.4 and aspida 1.7.1 now.

When I add this plugin, Typescript (tsc) drops version to 3.9.6, then other modules that support Typescript 4 or higher stop working.

Other ESlint plugins seem to have most of the modules they depend on in devDependencies, so I suppose the modules in dependencies (typescript, @typescript-eslint/experimental-utils, @types/eslint, @types/node) should be moved from dependencies to devDependencies.

## Environment

- **Package version:**
  
  `0.0.2`
- **OS:**
  
  - [ ] Linux
  - [x] Windows
  - [ ] macOS
- **Node.js version:**
  
  `v12.22.1`
- **npm version:**
  
  `yarn 1.22.5`

**Comment by LumaKernel** [comment]
This was resolved by https://github.com/aspida/eslint-plugin-aspida/pull/9

Thank you!
